#!/bin/bash

## Cluster_mode=[true|false],deafult is false
export Cluster_mode=""
export SSHPASS='123456'
Host=(
192.168.122.136
192.168.122.45
192.168.122.208
192.168.122.31
)
export title="系统信息报告"
export HOST=$(hostname)
